C#/Blog/Blog/Models/Article.cs
using Blog.Data;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Blog.Models
{
    public class Article
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        public string Content { get; set; }

        public DateTime DateAdded { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public Article()
        {
            this.DateAdded = DateTime.Now;
        }

        public bool IsAuthor(string name)
        {
             return this.Author.UserName.Equals(name);
        }
    }
}

C#/Blog/Blog/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public string AuthorId { get; set; }

        public ArticleViewModel(int id, string title, string content)
        {
            this.Id = id;
            this.Title = title;
            this.Content = content;
        }

        public ArticleViewModel()
        {
        }
    }
}

C#/Blog/Blog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Blog.Data;
using Blog.Models;
using Microsoft.AspNetCore.Authorization;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly ApplicationDbContext db;

        public ArticleController(ApplicationDbContext dbContext)
        {
            this.db = dbContext;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult List()
        {
            List<Article> articles = db.Articles
                .Include(a => a.Author)
                .OrderByDescending(x => x.DateAdded)
                .ToList();

            return View(articles);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return StatusCode(500);
            }

            Article article = db.Articles
                .Include(a => a.Author)
                .FirstOrDefault(a => a.Id == id);

            if (article == null)
            {
                return StatusCode(500);
            }

            return View(article);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Article article)
        {

            if (ModelState.IsValid)
            {
                string authorId = db.Users
                    .Where(u => u.UserName == this.User.Identity.Name)
                    .First()
                    .Id;
                article.AuthorId = authorId;

                db.Articles.Add(article);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(article);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return StatusCode(500);
            }

            if (IsUserAuthorizedToEdit(article) == false)
            {
                return Forbid();
            }


            return View(article);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(Article article)
        {

            if (article == null)
            {
                return NotFound();
            }

            db.Articles.Remove(article);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Article article = db.Articles.Find(id);

            if (article == null)
            {
                return NotFound();
            }

            if (IsUserAuthorizedToEdit(article) == false)
            {
                return Forbid();
            }

            ArticleViewModel articleModel = new ArticleViewModel(article.Id, article.Title, article.Content);

            return View(articleModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(ArticleViewModel articleModel)
        {
            if (ModelState.IsValid)
            {
                Article article = db.Articles
                .FirstOrDefault(a => a.Id == articleModel.Id);

                article.Title = articleModel.Title;
                article.Content = articleModel.Content;

                db.Articles.Update(article);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
            return View(articleModel);
        }

        public bool IsUserAuthorizedToEdit(Article article)
        {
            string authorId = db.Users.
                Where(u => u.UserName == this.User.Identity.Name)
                .First()
                .Id;
            bool isAdmin = this.User.IsInRole("Admin");
            bool isAuthor = article.AuthorId == authorId;

            return isAdmin || isAuthor;
        }

        [HttpGet]
        public ActionResult MyArticles()
        {
            string authorId = db.Users
                    .Where(u => u.UserName == this.User.Identity.Name)
                    .First()
                    .Id;

            List<Article> articles = db.Articles
                .Where(a => a.AuthorId == authorId)
                .OrderByDescending(x => x.DateAdded)
                .ToList();

            return View(articles);
        }

    }
}

C#/Blog/Blog/Views/Article/Create.cshtml
@model Article
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Article</h2>
        <form asp-action="Create" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label col-sm-4"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label col-sm-4"></label>
                <textarea asp-for="Content" class="form-control" rows="7"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    <a asp-action="Index" class="btn btn-default">Cancel</a>
                    <input type="submit" value="Create" class="btn btn-success"/>
                </div>
            </div>
        </form>
    </div>
</div>

C#/Blog/Blog/Views/Article/Delete.cshtml
@model Article

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Article</h2>
        <form asp-action="Delete" class="form-horizontal">
            <div class="form-group">
                <label asp-for="Title" class="control-label col-sm-4"></label>
                <input asp-for="Title" class="form-control" readonly />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label col-sm-4"></label>
                <textarea asp-for="Content" class="form-control" rows="7" readonly></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    <input type="hidden" asp-for="Id" />
                    <a asp-action="Index" class="btn btn-default">Cancel</a>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

C#/Blog/Blog/Views/Article/Details.cshtml
@model Article

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <article>
        <header>
            <h2>
                @Model.Title
            </h2>
        </header>
        <p>
            @Html.DisplayFor(model => model.Content)
        </p>
        <small class="author">
            -- date: @Html.DisplayFor(model => model.DateAdded)
        </small>
        <small class="author">
            -- author @Html.DisplayFor(model => model.Author.FullName)
        </small>
        <footer class="pull-right">
            @if (User.IsInRole("Admin") || Model.IsAuthor(this.User.Identity.Name))
            {
                <a class="btn btn-success btn-xs" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                <a class="btn btn-danger btn-xs" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            }
            
            <a class="btn btn-default btn-xs" asp-action="Index">Back</a>
        </footer>
    </article>
</div>

C#/Blog/Blog/Views/Article/Edit.cshtml
@model ArticleViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Article</h2>
        @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

C#/Blog/Blog/Views/Article/List.cshtml
@model List<Article>

@{
    ViewData["Title"] = "List";
}

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-sm-6">
                <article>
                    <header>
                        <h2>
                            <a asp-action="Details" asp-route-id="@article.Id">@article.Title</a>
                        </h2>
                    </header>
                    <p>
                        @Html.DisplayFor(modelItem => article.Content)
                    </p>
                    <footer class="pull-right">
                        <small>
                            @Html.DisplayFor(modelItem => article.DateAdded)
                        </small>
                        <small class="author">
                            @Html.DisplayFor(modelItem => article.Author.FullName)
                        </small>
                    </footer>
                </article>
            </div>
        }
    </div>
</div>

C#/Blog/Blog/Views/Article/MyArticles.cshtml
@model List<Article>

@{
    ViewData["Title"] = "List";
}

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-sm-6">
                <article>
                    <header>
                        <h2>
                            <a asp-action="Details" asp-route-id="@article.Id">@article.Title</a>
                        </h2>
                    </header>
                    <p>
                        @Html.DisplayFor(modelItem => article.Content)
                    </p>
                    <small class="author">
                        @Html.DisplayFor(modelItem => article.DateAdded)
                    </small>
                    <footer class="pull-right">
                        <a class="btn btn-success btn-xs" asp-action="Edit" asp-route-id="@article.Id">Edit</a>
                        <a class="btn btn-danger btn-xs" asp-action="Delete" asp-route-id="@article.Id">Delete</a>
                    </footer>
                </article>
            </div>
        }
    </div>
</div>